### ISSUE TITLE
Ubuntu 20.10 Groovy Gorilla end of life

### ISSUE THREAD

**Issue by msamendinger** [thomasWeise/docker-texlive#6]
Hi,

first of all thank you for providing this docker image.
I'm using it to write documentation in tex and creating pdfs with a github actions workflow.

When running the GitHub action I need to install additional packets but that doesn't work anymore as groovy is end of live and I receive the error 
> The repository 'http://security.ubuntu.com/ubuntu groovy Release' does not have a Release file.

Digging through your `Dockerfiles` it seems like `docker-texlive` is based on `docker-pandoc` which is based on  `docker-texlive-thin` which got already updated to [ubuntu 22.04](https://github.com/thomasWeise/docker-texlive-thin/blob/91be46c5d1a91be3f401a007fff66302cc37711a/image/Dockerfile#L12) but there is no automatic rebuild in place.

For my use case it was fine to just switch to [`docker-textlive-thin`](https://github.com/thomasWeise/docker-texlive-thin/) but still wanted to leave a comment, last but not least to thank you for your work.

**Comment by thomasWeise** [comment]
Thank you.
I made a new version, 2.0, which uses Ubuntu 22.04.
But it is for docker-texlive-full.
I do not really maintain this image here actively anymore.
Sorry, I was a bit busy lately, so I did not get to it any sooner.
Cheers,
   Thomas.
